baseURL = "https://bgood35.github.io/"
languageCode = "en-us"
title = "Brandon G"
theme = "PaperMod"
paginate = 5

[params]
  author = "Brandon Goodman"
  description = "Brandon Goodman is an Integrated Marketing leader with 15+ years of experience stewarding $100M+ portfolios for global brands like Google, Campbell's Snacks, and Groupe Bel. Expert in modernizing operating models, AEO/GEO roadmaps, and audience-led strategy. Brand Innovators 40 Under 40 honoree and creator of Media Musings."
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
defaultTheme = "light"
disableThemeToggle = true

[params.homeInfoParams]
  Title = ""
  Content = "Connect"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/brandon-goodman-bb18b793/"

[menu]
  [[menu.main]]
    name = "Thoughts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Past Work"
    url = "/portfolio/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true